on:
  push:
    tags:
      - "v*"
name: Check package version
jobs:
  checkVersion:
    name: Check package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use this GitHub Action
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
